In [1]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensors
### Creating tensors
pytorch tensors are created using `torch.tensor()`

In [ ]:
### scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [ ]:
### vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [ ]:
### MATRIX
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 3])

In [11]:
MATRIX[0]

tensor([1, 2, 3])

In [12]:
MATRIX[0,1]

tensor(2)

In [ ]:
### TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
        ]
    ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
random tensors can create by using `torch.rand()`

In [21]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5808, 0.7749, 0.8043, 0.6073],
        [0.3775, 0.2591, 0.0172, 0.1783],
        [0.6244, 0.1716, 0.2343, 0.3195]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor.shape

torch.Size([3, 4])

In [25]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)