In [1]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensors
### Creating tensors
pytorch tensors are created using `torch.tensor()`

In [2]:
### scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
### vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
### MATRIX
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 3])

In [11]:
MATRIX[0]

tensor([1, 2, 3])

In [12]:
MATRIX[0,1]

tensor(2)

In [13]:
### TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
        ]
    ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
random tensors can create by using `torch.rand()`

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7015, 0.4089, 0.4018, 0.1208],
        [0.4328, 0.7143, 0.8565, 0.7351],
        [0.5937, 0.9646, 0.7525, 0.0081]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [20]:
# Create zeros tensor
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create ones tensor
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tesnors-like

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(1,10,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [25]:
# Creating tesnors like
zeros_like = torch.zeros_like(one_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0])

### Tensor datatype

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([4,4.0])
float_32_tensor , float_32_tensor.dtype

(tensor([4., 4.]), torch.float32)

In [27]:
float_16_tensor = torch.tensor([4,4.0],dtype=torch.half)
float_16_tensor , float_16_tensor.dtype

(tensor([4., 4.], dtype=torch.float16), torch.float16)

In [28]:
float_16_tensor_v2 = float_32_tensor.type(torch.half)
float_16_tensor_v2 , float_16_tensor_v2.dtype

(tensor([4., 4.], dtype=torch.float16), torch.float16)

In [29]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors


In [30]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8591, 0.4329, 0.1074, 0.6805],
        [0.2326, 0.7249, 0.8635, 0.5170],
        [0.9570, 0.7632, 0.2984, 0.5701]])

In [31]:
# Information of tensor
print("shape:",some_tensor.shape)
print("size:",some_tensor.size())
print("device:",some_tensor.device)
print("dim:",some_tensor.ndim)
print("dtype:",some_tensor.dtype)

shape: torch.Size([3, 4])
size: torch.Size([3, 4])
device: cpu
dim: 2
dtype: torch.float32


### Manipulating Tensors

In [32]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [33]:
tensor * 10

tensor([10, 20, 30])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [36]:
# Pytorch built-in function
print(f"add: {torch.add(tensor,10)}")
print(f"subtract:",torch.subtract(tensor,10))
print(f"multiply:",torch.multiply(tensor,10))
print(f"mul:",torch.mul(tensor,10))
print(f"divide:",torch.divide(tensor,10))

add: tensor([11, 12, 13])
subtract: tensor([-9, -8, -7])
multiply: tensor([10, 20, 30])
mul: tensor([10, 20, 30])
divide: tensor([0.1000, 0.2000, 0.3000])


In [37]:
### Element-wise multipication
print(tensor)
print(tensor*tensor)
print(torch.mul(tensor,tensor))
print(torch.multiply(tensor,tensor))

tensor([1, 2, 3])
tensor([1, 4, 9])
tensor([1, 4, 9])
tensor([1, 4, 9])


In [38]:
### Matrix Multipication
print(tensor @ tensor)
print(torch.matmul(tensor,tensor)) 

tensor(14)
tensor(14)


In [39]:
%%timeit
torch.matmul(tensor,tensor)

1.12 μs ± 28.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [40]:
%%timeit
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]


19.4 μs ± 678 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [41]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [42]:
print(tensor_B)
print(tensor_B.T)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [43]:
tensor_A.T , tensor_A.T.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [44]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [45]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [46]:
torch.mm(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [100, 136]])

### Tensor Aggregation

In [47]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [48]:
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [49]:
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [50]:
# torch.mean(x),x.mean() --> error
torch.mean(x.type(torch.float16)),x.type(torch.float16).mean()

(tensor(45., dtype=torch.float16), tensor(45., dtype=torch.float16))

In [51]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Find Position of max and min of tensor

In [52]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [54]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [55]:
x[x.argmax().item()] == x.max()

tensor(True)

In [56]:
x[x.argmin().item()] == x.min()

tensor(True)

### Reshaping, Stacking, Sqeezing tensors

In [57]:
x = torch.arange(1,10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [58]:
# maltipication reshape size need to = shape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [59]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [60]:
# change the view
x_view = x.view(1,9)
x_view , x_view.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [61]:
# changin x_view changes original x 
x_view[:,0]=5
x_view , x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [62]:
# stack
x_stack = torch.stack([x,x,x],dim=0)
x_stack

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [63]:
x_stack = torch.stack([x,x,x],dim=1)
x_stack

tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [64]:
x_hstack = torch.hstack([x,x,x])
x_hstack

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 2, 3, 4, 5, 6,
        7, 8, 9])

In [65]:
x_vstack = torch.vstack([x,x,x])
x_vstack

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# Squeeze --> remove all single dim (1 dim)
x_reshaped

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [72]:
x_reshaped.shape

torch.Size([9, 1])

In [75]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
x_squeezed.shape

torch.Size([9])

In [ ]:
# Unsqueeze --> add single dimension (1 dim)
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [80]:
x_unsqueezed.shape

torch.Size([1, 9])

In [82]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [83]:
x_unsqueezed.shape

torch.Size([9, 1])

In [ ]:
# Permute --> permute element 
x_original = torch.randn(224,224,3)
x_original.shape

torch.Size([224, 224, 3])

In [86]:
x_original.permute(2,0,1).shape

torch.Size([3, 224, 224])