In [3]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

In [ ]:
MATRIX[0]

tensor([1, 2, 3])

In [ ]:
MATRIX[0,1]

tensor(2)

In [ ]:
# TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
        ]
    ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])