In [1]:
import numpy as np
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


## Introduction to Tensors
### Creating tensors
pytorch tensors are created using `torch.tensor()`

In [ ]:
### scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [ ]:
### vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [ ]:
### MATRIX
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 3])

In [11]:
MATRIX[0]

tensor([1, 2, 3])

In [12]:
MATRIX[0,1]

tensor(2)

In [ ]:
### TENSOR
TENSOR = torch.tensor([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
        ]
    ])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors
random tensors can create by using `torch.rand()`

In [21]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5808, 0.7749, 0.8043, 0.6073],
        [0.3775, 0.2591, 0.0172, 0.1783],
        [0.6244, 0.1716, 0.2343, 0.3195]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor.shape

torch.Size([3, 4])

In [25]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create zeros tensor
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create ones tensor
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

### Creating a range of tensors and tesnors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1,10,2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [35]:
# Creating tesnors like
zeros_like = torch.zeros_like(one_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0])

### Tensor datatype

In [37]:
# Float 32 tensor
float_32_tensor = torch.tensor([4,4.0])
float_32_tensor , float_32_tensor.dtype

(tensor([4., 4.]), torch.float32)

In [42]:
float_16_tensor = torch.tensor([4,4.0],dtype=torch.half)
float_16_tensor , float_16_tensor.dtype

(tensor([4., 4.], dtype=torch.float16), torch.float16)

In [44]:
float_16_tensor_v2 = float_32_tensor.type(torch.half)
float_16_tensor_v2 , float_16_tensor_v2.dtype

(tensor([4., 4.], dtype=torch.float16), torch.float16)

In [48]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors


In [49]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8245, 0.3976, 0.2753, 0.8914],
        [0.4270, 0.8204, 0.5481, 0.9183],
        [0.9564, 0.0953, 0.1633, 0.8816]])

In [ ]:
# Information of tensor
print("shape:",some_tensor.shape)
print("size:",some_tensor.size())
print("device:",some_tensor.device)
print("dim:",some_tensor.ndim)
print("dtype:",some_tensor.dtype)

tensor: tensor([[0.8245, 0.3976, 0.2753, 0.8914],
        [0.4270, 0.8204, 0.5481, 0.9183],
        [0.9564, 0.0953, 0.1633, 0.8816]])
shape: torch.Size([3, 4])
size: torch.Size([3, 4])
device: cpu
dim: 2
dtype: torch.float32
